# Generated by Django 5.2.12 on 2026-03-26 18:37

import django.db.models.deletion
from django.db import migrations, models


def backfill_question_subject(apps, schema_editor):
    Question = apps.get_model('quiz', 'Question')
    for question in Question.objects.select_related('quiz', 'quiz__subject').all():
        if question.subject_id is None and question.quiz_id and question.quiz.subject_id:
            question.subject_id = question.quiz.subject_id
            question.save(update_fields=['subject'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_quiz_max_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.subject'),
        ),
        migrations.RunPython(backfill_question_subject, noop_reverse),
    ]
